"""Lexical resources: the attested syllable inventory and word lists.

Resources live under data/external/ and are fetched by scripts/fetch_resources.py:
  vi-DauMoi.dic  Hunspell vi_VN syllable list, new tone placement (6,642 lines; GPLv2)
  vi-DauCu.dic   the same list in old tone placement
  Viet74K.txt    Hồ Ngọc Đức's word list, about 74k words and phrases (GPL)

Licensing decision (docs/DESIGN_DECISIONS.md 4.1, 11.1, 12.22): these lists are
consulted at build time (legality, lexicality, frequency proxies); the released items are
generated by the rule engine, but the lexical items reproduce N Viet74K two-syllable entries
verbatim as inputs or gold, N counted in the release manifest (the lexical base pairs of the
release; `n_lexical_base_pairs`, to be emitted next to `n_base_pairs`), under the terms
DESIGN_DECISIONS 4.1 / 11.1 state (written permission requested; GPLv2 with attribution as
the fallback). The Hunspell syllable inventory is not redistributed.
"""
from __future__ import annotations

import re
from collections import Counter
from collections.abc import Iterable
from functools import cache
from pathlib import Path

from . import unicode as U
from .syllable import Inventory, try_parse

ROOT = Path(__file__).resolve().parents[2]
EXTERNAL = ROOT / "data" / "external"

_WORD_RE = re.compile(r"^[a-zđÀ-ɏḀ-ỿ]+$")


def _read_lines(path: Path) -> list[str]:
    with open(path, encoding="utf-8") as f:
        return [ln.rstrip("\n") for ln in f]


def load_hunspell_syllables(style: str = "new") -> list[str]:
    """Lowercase, NFC syllables from the Hunspell list (proper nouns and acronyms dropped)."""
    name = "vi-DauMoi.dic" if style == "new" else "vi-DauCu.dic"
    lines = _read_lines(EXTERNAL / name)[1:]  # first line is the count
    out = []
    for w in lines:
        w = U.nfc(w.strip())
        if not w or not w.islower():
            continue
        if not _WORD_RE.match(w):
            continue
        out.append(w)
    return out


WORDLIST_MIN_COUNT = 2
CACHE = ROOT / "data" / "cache"


def _file_sha256(path: Path) -> str:
    import hashlib
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


@cache
def wordlist_index(name: str = "Viet74K.txt") -> dict:
    """Parsed view of the word list, cached on disk under data/cache keyed by the file hash:
      canonical_counts        canonical spelling -> number of entries containing the syllable
      strict_standard_counts  standard-spelled syllables (strict parse) -> count
      two_syllable_pairs      [[a, b], ...] canonical spellings of two-syllable entries
    Parsing the 74k entries takes about 15 s; the cache makes every later load instant."""
    import json
    path = EXTERNAL / name
    key = _file_sha256(path)[:16]
    CACHE.mkdir(parents=True, exist_ok=True)
    cpath = CACHE / f"wordlist_{name}_{key}_v2.json"
    if cpath.exists():
        with open(cpath, encoding="utf-8") as f:
            return json.load(f)
    from .syllable import spell
    canonical: Counter = Counter()
    strict: Counter = Counter()
    surface_iy: Counter = Counter()
    pairs: list[list[str]] = []
    for w in load_words(name):
        parts = w.split()
        parsed = [try_parse(p, strict=False) for p in parts]
        for part, pr in zip(parts, parsed):
            if pr is None:
                continue
            canonical[spell(pr.syllable)] += 1
            if pr.i_y_variant is None and try_parse(part, strict=True) is not None:
                strict[part] += 1
            sy = pr.syllable
            if sy.nucleus == "i" and not sy.glide and sy.coda == "":
                surface_iy[part] += 1                 # both spellings of a bare /i/ (lí and lý) as written
        if len(parts) == 2 and all(parsed):
            pairs.append([spell(parsed[0].syllable), spell(parsed[1].syllable)])
    data = {"source": name, "sha256_prefix": key, "canonical_counts": dict(canonical),
            "strict_standard_counts": dict(strict), "surface_counts_iy": dict(surface_iy), "two_syllable_pairs": pairs}
    tmp = cpath.with_suffix(".tmp")
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False)
    tmp.replace(cpath)
    return data


@cache
def load_inventory(extended: bool = True) -> Inventory:
    """The attested syllable inventory.

    Base: the Hunspell list in both placement styles (6,611 lowercase entries). The
    Hunspell list misses a number of common syllables (gẫy, nhếch, cược, thới, ...), so
    `extended=True` (the default) adds every syllable of the Viet74K word list that
    parses in strict mode with a standard spelling and occurs in at least
    WORDLIST_MIN_COUNT entries (singletons are likely typos or proper-noun fragments).
    The extension adds a few hundred syllables and no new rime types are accepted
    unless they are attested this way.
    """
    base = load_hunspell_syllables("new") + load_hunspell_syllables("old")
    if not extended:
        return Inventory(base)
    counts = wordlist_index()["strict_standard_counts"]
    base_inv = Inventory(base)
    hun = set(base)
    extra = []
    for syl, n in counts.items():
        if n < WORDLIST_MIN_COUNT or syl in hun:
            continue
        pr = try_parse(syl, strict=True)
        # no new RIME types from the word list: a rime unattested in the Hunspell base is
        # more likely a foreign word or a typo (ii, quới) than a gap in the base
        if pr is None or pr.syllable.rime not in base_inv.rimes:
            continue
        extra.append(syl)
    inv = Inventory(base + sorted(extra))
    inv.n_extended = len(extra)
    return inv


def load_words(name: str = "Viet74K.txt") -> list[str]:
    """Lowercase NFC entries of a word list (multi-syllable entries are space separated)."""
    out = []
    for w in _read_lines(EXTERNAL / name):
        w = U.nfc(w.strip().lower())
        if w:
            out.append(w)
    return out


def two_syllable_words(words: Iterable[str]) -> list[tuple[str, str]]:
    """Entries that are exactly two parseable syllables."""
    pairs = []
    for w in words:
        parts = w.split()
        if len(parts) != 2:
            continue
        if all(try_parse(p, strict=False) for p in parts):
            pairs.append((parts[0], parts[1]))
    return pairs


def syllable_frequencies(words: Iterable[str] | None = None) -> Counter:
    """How often each canonical syllable appears across the word list (a frequency proxy).
    With no argument the cached index of Viet74K is used."""
    if words is None:
        return Counter(wordlist_index()["canonical_counts"])
    c: Counter = Counter()
    for w in words:
        for p in w.split():
            pr = try_parse(p, strict=False)
            if pr:
                c[pr.syllable.spelled()] += 1
    return c


def lexical_pairs() -> set[tuple[str, str]]:
    """Canonical two-syllable entries of the word list (cached)."""
    return {tuple(p) for p in wordlist_index()["two_syllable_pairs"]}


# ---------------------------------------------------------------- emission (design 2.2 R5, items 2 and 11)
# Zero-onset bare /i/: the lexicon form per tone (vi-DauMoi has y ý ỷ and ì í ỉ, none of ỳ ỵ ỹ).
ZERO_ONSET_I = {0: "y", 1: "ì", 2: "ý", 3: "ỷ", 4: "ĩ", 5: "ị"}
_NEVER_Y_ONSETS = frozenset({"s", "v"})      # sĩ 118 vs sỹ 2, vĩ 34 vs vỹ 0 in Viet74K; sỹ survives in names


@cache
def iy_table() -> dict:
    """Per-syllable i/y choice for a bare /i/ after a consonant onset: the form with the higher
    count in the reference corpus (fallback: Viet74K syllable-in-entry counts). Keys are the
    i-form spelling (standard, new style), values 'i' or 'y'. Ties and absent forms -> 'i'.
    The reference-corpus table (design 8.4) replaces this when the author supplies it as
    data/iy_table.json ({"lí": "y", ...})."""
    import json
    override = ROOT / "data" / "iy_table.json"
    if override.exists():
        return json.loads(override.read_text(encoding="utf-8"))
    counts = wordlist_index()["surface_counts_iy"]
    table = {}
    from .syllable import spell, try_parse
    for w in counts:
        p = try_parse(w, strict=False)
        if p is None:
            continue
        s = p.syllable
        if s.nucleus != "i" or s.glide or s.coda or s.onset == "":
            continue
        i_form = spell(s)                               # standard i spelling
        key = i_form
        y_form = i_form[:-1] + U.compose_letter("y", "", s.tone)
        ci = counts.get(i_form, 0)
        cy = counts.get(y_form, 0)
        table[key] = "y" if (cy > ci and s.onset not in _NEVER_Y_ONSETS) else "i"
    return table


def emit(syl, style: str = "old", inventory=None) -> str:
    """Spell a syllable for release: the tone mark per `style`; for a bare /i/ after a consonant
    the per-syllable majority form (iy_table; never y after s/v); for a zero-onset bare /i/ the
    lexicon form per tone. Everything else is the standard spelling."""
    from .syllable import spell
    std = spell(syl, style=style)
    if syl.nucleus == "i" and not syl.glide and syl.coda == "":
        if syl.onset == "":
            return ZERO_ONSET_I[syl.tone]
        if syl.onset in _NEVER_Y_ONSETS:
            return std
        if iy_table().get(spell(syl), "i") == "y":
            return std[:-1] + U.compose_letter("y", "", syl.tone)
    return std


def iy_form(word: str) -> str | None:
    """'i' or 'y' for a bare-/i/ syllable as written, else None (the i_y covariate)."""
    from .syllable import try_parse
    p = try_parse(word, strict=False)
    if p is None or p.syllable.nucleus != "i" or p.syllable.glide or p.syllable.coda:
        return None
    return "y" if U.strip_tones(word)[-1] == "y" else "i"


def emit_phrase(sylls, style: str = "old", inventory=None) -> str:
    return " ".join(emit(s, style, inventory) for s in sylls)
