"""Lexical resources: the attested syllable inventory and word lists.

Resources live under data/external/ and are fetched by scripts/fetch_resources.py:
  vi-DauMoi.dic  Hunspell vi_VN syllable list, new tone placement (6,642 lines; GPLv2)
  vi-DauCu.dic   the same list in old tone placement
  Viet74K.txt    Hồ Ngọc Đức's word list, about 74k words and phrases (GPL)

Licensing decision (see docs/DESIGN_DECISIONS.md, section 4): these lists are used
as lookups at generation time (legality, lexicality, frequency proxies) and are
never redistributed; the released items are generated by the rule engine.
"""
from __future__ import annotations

import os
import re
from collections import Counter
from functools import lru_cache
from pathlib import Path
from typing import Iterable

from . import unicode as U
from .syllable import Inventory, try_parse

ROOT = Path(__file__).resolve().parents[2]
EXTERNAL = ROOT / "data" / "external"

_WORD_RE = re.compile(r"^[a-zđÀ-ɏḀ-ỿ]+$")


def _read_lines(path: Path) -> list[str]:
    with open(path, encoding="utf-8") as f:
        return [ln.rstrip("\n") for ln in f]


def load_hunspell_syllables(style: str = "new") -> list[str]:
    """Lowercase, NFC syllables from the Hunspell list (proper nouns and acronyms dropped)."""
    name = "vi-DauMoi.dic" if style == "new" else "vi-DauCu.dic"
    lines = _read_lines(EXTERNAL / name)[1:]  # first line is the count
    out = []
    for w in lines:
        w = U.nfc(w.strip())
        if not w or not w.islower():
            continue
        if not _WORD_RE.match(w):
            continue
        out.append(w)
    return out


@lru_cache(maxsize=None)
def load_inventory() -> Inventory:
    """The attested syllable inventory (both placement styles merged, canonical spelling)."""
    return Inventory(load_hunspell_syllables("new") + load_hunspell_syllables("old"))


def load_words(name: str = "Viet74K.txt") -> list[str]:
    """Lowercase NFC entries of a word list (multi-syllable entries are space separated)."""
    out = []
    for w in _read_lines(EXTERNAL / name):
        w = U.nfc(w.strip().lower())
        if w:
            out.append(w)
    return out


def two_syllable_words(words: Iterable[str]) -> list[tuple[str, str]]:
    """Entries that are exactly two parseable syllables."""
    pairs = []
    for w in words:
        parts = w.split()
        if len(parts) != 2:
            continue
        if all(try_parse(p, strict=False) for p in parts):
            pairs.append((parts[0], parts[1]))
    return pairs


def syllable_frequencies(words: Iterable[str]) -> Counter:
    """How often each canonical syllable appears across the word list (a frequency proxy)."""
    c: Counter = Counter()
    for w in words:
        for p in w.split():
            pr = try_parse(p, strict=False)
            if pr:
                c[pr.syllable.spelled()] += 1
    return c
