#!/usr/bin/env python
"""Compute chunks: `configs/run_plan.yaml` cut into Kaggle sessions, in the order that keeps what the
pre-registered cut order keeps longest (docs/COMPUTE_PLAN.md).

    python scripts/plan_chunks.py --write    # configs/compute_chunks.yaml, notebooks/chunks/*.ipynb and the
                                             # generated block of docs/COMPUTE_PLAN.md
    python scripts/plan_chunks.py --check    # drift check (tests/test_cloud.py)
    python scripts/plan_chunks.py --table    # print the generated tables

A chunk is one Kaggle session: an ordered list of jobs `{run, models, overrides, tag}` that the T4 / TPU notebook's
run cell executes with `--resume` (a chunk notebook is that notebook with its parameters cell preset). A job that
narrows its run line (`overrides`, e.g. the third paraphrase alone) writes its own run directory
`data/runs/<run>__<model>__<tag>` (kaggle_run_plan.narrow_run), so a later cut can drop it whole.

Order (the reverse of the pre-registered cut order: what is cut first runs last). DESIGN_DECISIONS 7.1 / PREREG:
"tokenizer-redundant models first (Gemma 3 12B, Qwen3.5-0.8B, Gemma 4 12B), then the second model of any family,
then seeds/paraphrases per 8.5"; DD 8.5: above 120 GPU-h, "E3's full arms are capped to the C1-informative families
and paraphrases drop to two for the TPU/2xT4 models before any model is cut in the 7.1 order". Tiers:

    0  pre-stage-2 lines on dev (smoke, pilot): not cuttable, and the only lines allowed before the stage-2 commit
    1  the first model of each family on every main line                       (cut last: never in the order)
    2  lines the cut order does not name, on tier-1 models: ablations, reasoning, bf16 drift
    3  the second model of a family                                             (cut stage 2 of DD 7.1)
    4  the tokenizer-redundant models                                           (cut stage 1 of DD 7.1)
    5  p2 of the TPU / 2xT4 models; E3 arms of families the census marks normalizing   (DD 8.5: cut before any model)

The 7.1 "seeds/paraphrases" stage (cut after the second models) is not split out: every model's p0-p2 run in one
job except where DD 8.5 needs p2 apart. Estimates: the plan's line estimate split EQUALLY over the line's models
(one stated rule; E1_main excludes the TPU trio that `tpu_main` books); a TPU model's share of a gpu_hours line is
spent on the TPU and booked on no plan line (flagged `unbooked`). Every number is "plan estimate, re-priced after
the smoke week" (DD 8.5 item 30); none is a measurement. Quota readings: x1 = a 2xT4 session hour costs one quota
hour, x2 = two [UNCERTAIN: verify in Kaggle's settings page].
"""
from __future__ import annotations

import argparse
import copy
import json
import pprint
import re
import sys
from pathlib import Path

import nbformat

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parent))
import kaggle_build_notebooks as KBN
import kaggle_run_plan as KRP

ROOT = Path(__file__).resolve().parents[1]
CHUNKS_YAML = ROOT / "configs" / "compute_chunks.yaml"
CHUNK_DIR = ROOT / "notebooks" / "chunks"
COMPUTE_PLAN = ROOT / "docs" / "COMPUTE_PLAN.md"
BENCH = ROOT / "data" / "audit" / "cpu_bench_gemma3_1b_shape.json"
BEGIN, END = "<!-- plan_chunks:begin (generated by scripts/plan_chunks.py; do not edit by hand) -->", "<!-- plan_chunks:end -->"

REDUNDANT = ("gemma-3-12b-it", "qwen3.5-0.8b", "gemma-4-12b")      # DD 7.1, in its order; tests pin the DD sentence
PILOT_SET = "pilot"
SESSION_CAP_H = {"gpu": 8.0, "tpu": 7.0, "cpu": 10.0}   # high estimate one chunk may book: the T4 notebook launches no model
                                                       # past 9 h, the TPU one past 8 h, the CPU one past 10 h; the rest is
                                                       # install, model loads and pushes
SESSION_OVERHEAD_H = 0.5   # planning assumption per session (install, loads, pushes) [UNCERTAIN: measure in the smoke week]
QUEUE_NOTEBOOK = {"gpu": "kaggle_eval_t4", "tpu": "kaggle_eval_tpu", "cpu": "kaggle_cpu_pilot"}
HW_QUEUE = {"t4": "gpu", "2xt4": "gpu", "tpu": "tpu", "cpu": "cpu"}
MAIN_LINES = ("E1_main", "tpu_main", "E1_explicit_input", "E3_noilai", "E3_xcopa", "E3_c2_enriched", "E1_attested",
              "E3_scope_item", "E3_engine_hf")
OUTSIDE_LINES = ("E1_abl_zero_shot", "E1_abl_name_only", "E1_abl_english", "E1_abl_spaced", "reasoning_500",
                 "reasoning_500_tpu", "bf16_drift_200")
E3_LINES = ("E3_noilai", "E3_xcopa", "E3_c2_enriched")
P2_SPLIT_LINES = ("E1_main", "tpu_main", "E1_attested")   # lines with p0-p2 whose p2 DD 8.5 cuts for TPU/2xT4 models
PRE_LINES = ("smoke_20", "smoke_20_tpu", "pilot_t1_200", "pilot_xcopa_200")
NOT_CHUNKED = {"api": "API lines are bounded by the providers' daily caps, not by sessions: notebooks/api_runs.ipynb, "
                      "re-run daily (the ledger parks a model at its cap)",
               "E4_probe": "not a run_eval line; notebooks/colab_probe_gemma3.ipynb is a skeleton without resume (the E4 "
                           "protocol is a stage-2 item); window 23 Nov-6 Dec, after the results freeze"}
TIER_LABEL = {
    0: "pre-stage-2, dev split only (smoke, pilot)",
    1: "first model of each family, main lines (never cut)",
    2: "lines outside the cut order on tier-1 models (ablations, reasoning, bf16 drift)",
    3: "second model of a family (DD 7.1 cut stage 2)",
    4: "tokenizer-redundant models (DD 7.1 cut stage 1)",
    5: "p2 of TPU/2xT4 models; E3 of normalizing families (DD 8.5: cut first)",
}
WINDOW = {0: "now - 25 Oct (Gate 1 on 18 Oct; panel freeze 25 Oct)",
          **{t: "after the stage-2 commit (DD 8.8) - 22 Nov (Gate 3, results freeze)" for t in range(1, 6)}}
STAGE2_SCENARIOS = (("8 Nov (DD 8.8 latest)", 2), ("1 Nov", 3), ("25 Oct (right after the panel freeze: the earliest)", 4))
CPU_PARAM_SCALE = {"gemma-3-1b-it": 1.0, "qwen3.5-2b": 2.0, "phogpt-4b-chat": 3.7}   # ~ parameter count / gemma-3-1b-it's
                                                                                    # [UNCERTAIN: Qwen3.5-2B's size unverified]


# --------------------------------------------------------------------------------------------- model roles
def model_hw(name: str, mc: dict) -> str:
    return mc["by_name"][name].get("hardware")


def first_of_family(plan: dict, mc: dict) -> dict[str, str]:
    """{family: lead model}: the pilot model of the family if it has one, else the first non-redundant self-hosted entry
    of configs/models.yaml (a scheduling rule, not a pre-registered one: docs/COMPUTE_PLAN.md, question to the author)."""
    pilot = KRP.expand_set(PILOT_SET, plan, mc)
    lead: dict[str, str] = {}
    for m in mc["models"]:
        if m.get("reference_of") or m.get("hardware") not in HW_QUEUE or m["name"] in REDUNDANT:
            continue
        fam = m.get("family")
        if fam not in lead or (m["name"] in pilot and lead[fam] not in pilot):
            lead[fam] = m["name"]
    return lead


def model_tier(name: str, plan: dict, mc: dict) -> int:
    """1 lead, 3 second of a family, 4 redundant (serving variants take their reference model's tier)."""
    base = mc["by_name"][name].get("reference_of") or name
    if base in REDUNDANT:
        return 4
    return 1 if base in first_of_family(plan, mc).values() else 3


def normalizes_nfd(name: str, mc: dict) -> bool:
    from noilai.eval.run import normalization_census_for
    c = normalization_census_for(mc["by_name"][name], {})
    return c.get("status") == "censused" and c.get("verdict_nfd") == "normalizes"


# --------------------------------------------------------------------------------------------- estimates
def booked_models(run: dict, plan: dict, mc: dict) -> list[str]:
    ms = KRP.expand_models(run, plan, mc)
    if run["id"] == "E1_main":                       # the TPU trio's part is booked under tpu_main (run_plan.yaml note)
        tpu_line = set(KRP.expand_models(KRP.find_run(plan, "tpu_main"), plan, mc))
        ms = [m for m in ms if m not in tpu_line]
    return ms


def share(run: dict, model: str, plan: dict, mc: dict) -> tuple[float, float, str]:
    """(low, high, booked_on): the line's estimate split equally over its models."""
    est = run["estimate"]
    n = len(booked_models(run, plan, mc))
    unit_q = {"gpu_hours": "gpu", "tpu_hours": "tpu"}.get(est["unit"])
    q = HW_QUEUE.get(model_hw(model, mc))
    if q is None:
        booked = None                                  # no queue for this hardware: make_jobs lists it as unscheduled
    else:
        booked = run.get("counts_toward") if unit_q == q else f"unbooked ({est['unit']} share run on the {q.upper()})"
    return est["low"] / n, est["high"] / n, booked


def cpu_estimates(bench: dict | None = None) -> dict:
    """Hours per CPU job for gemma-3-1b-it, derived from the RL-2026-10-01-06 benchmark (4 cores, float32): worst case
    64 new tokens per request, 8 forced-choice candidates per T1 item, XCOPA bounded by a 520-token prompt."""
    b = bench or json.loads(BENCH.read_text())
    dec520 = (b["generate_bs1_520p_24new_s"] - b["prefill_520_s"]) / 24
    dec950 = (b["generate_bs1_950p_24new_s"] - b["prefill_950_s"]) / 24
    gen_nfc, gen_nfd = b["prefill_520_s"] + 64 * dec520, b["prefill_950_s"] + 64 * dec950
    fc_nfc = b["prefill_520_s"] + 8 * b["continuation_3tok_on_cache_520_s"]
    fc_nfd = b["prefill_950_s"] + 8 * b["continuation_3tok_on_cache_950_s"]
    return {"smoke_20": 40 * gen_nfc / 3600,
            "pilot_t1_200": 200 * (gen_nfc + gen_nfd) / 3600,
            "pilot_t1_200_forced_choice": 200 * (fc_nfc + fc_nfd) / 3600,
            "pilot_xcopa_200": 200 * 2 * (b["prefill_520_s"] + 2 * b["continuation_3tok_on_cache_520_s"]) / 3600}


# --------------------------------------------------------------------------------------------- jobs
def make_jobs(plan: dict, mc: dict) -> tuple[list[dict], list[dict]]:
    """One job per (run, model[, paraphrase subset]) of every GPU/TPU line after tier 0; and the unscheduled ones."""
    jobs, unscheduled = [], []
    lines = [KRP.find_run(plan, r) for r in MAIN_LINES + OUTSIDE_LINES]
    for run in lines:
        for m in booked_models(run, plan, mc):
            hw = model_hw(m, mc)
            q = HW_QUEUE.get(hw)
            lo, hi, booked = share(run, m, plan, mc)
            if q is None:
                unscheduled.append({"run": run["id"], "model": m, "hours": [round(lo, 2), round(hi, 2)],
                                    "reason": f"configured for {hw!r}: no zero-cost route in the plan (Modal L4 needs a "
                                              "card on file, which this project does not use); question to the author"})
                continue
            tier = model_tier(m, plan, mc)
            if run["id"] in OUTSIDE_LINES and tier == 1 or run["id"] in ("reasoning_500", "reasoning_500_tpu"):
                tier = 2                              # reasoning is a sub-study of its own, outside the cut order
            if run["id"] in E3_LINES and normalizes_nfd(m, mc):
                tier = 5
            base = {"run": run["id"], "model": m, "queue": q, "booked_on": booked, "line_rank": (MAIN_LINES + OUTSIDE_LINES).index(run["id"])}
            if run["id"] in P2_SPLIT_LINES and hw in ("2xt4", "tpu") and run.get("paraphrases") == ["p0", "p1", "p2"]:
                jobs.append({**base, "tier": tier, "overrides": {"paraphrases": ["p0", "p1"]}, "tag": "p0p1",
                             "hours": [lo * 2 / 3, hi * 2 / 3]})
                jobs.append({**base, "tier": 5, "overrides": {"paraphrases": ["p2"]}, "tag": "p2", "hours": [lo / 3, hi / 3]})
            else:
                jobs.append({**base, "tier": tier, "overrides": None, "tag": None, "hours": [lo, hi]})
    return jobs, unscheduled


def model_order(mc: dict) -> dict[str, int]:
    return {m["name"]: i for i, m in enumerate(mc["models"])}


def pack(jobs: list[dict], queue: str, mc: dict) -> list[list[dict]]:
    """Greedy, tier-pure, model-major: a model's jobs of one tier stay in one chunk; a chunk books <= the cap."""
    order = model_order(mc)
    cap = SESSION_CAP_H[queue]
    chunks: list[list[dict]] = []
    for tier in range(1, 6):
        js = sorted((j for j in jobs if j["queue"] == queue and j["tier"] == tier),
                    key=lambda j: (order[j["model"]], j["line_rank"]))
        by_model: dict[str, list[dict]] = {}
        for j in js:
            by_model.setdefault(j["model"], []).append(j)
        cur, cur_h = [], 0.0
        for mjobs in by_model.values():
            h = sum(j["hours"][1] for j in mjobs)
            if h > cap:                                    # one model's tier work exceeds a session: split by job
                for j in mjobs:
                    if cur and cur_h + j["hours"][1] > cap:
                        chunks.append(cur)
                        cur, cur_h = [], 0.0
                    cur.append(j)
                    cur_h += j["hours"][1]
                continue
            if cur and cur_h + h > cap:
                chunks.append(cur)
                cur, cur_h = [], 0.0
            cur += mjobs
            cur_h += h
        if cur:
            chunks.append(cur)
    return chunks


def merge_jobs(js: list[dict]) -> list[dict]:
    """Notebook JOBS: run-major, consecutive models of one (run, overrides, tag) merged."""
    out: list[dict] = []
    for j in sorted(js, key=lambda j: j["line_rank"]):
        key = (j["run"], json.dumps(j["overrides"], sort_keys=True), j["tag"])
        if out and out[-1]["_key"] == key:
            out[-1]["models"].append(j["model"])
        else:
            out.append({"_key": key, "run": j["run"], "models": [j["model"]], "overrides": j["overrides"], "tag": j["tag"]})
    for o in out:
        del o["_key"]
    return out


# --------------------------------------------------------------------------------------------- chunks
def tier0_chunks(plan: dict, mc: dict) -> list[dict]:
    cpu = cpu_estimates()
    pilot = KRP.expand_set(PILOT_SET, plan, mc)
    out = [{"queue": "cpu", "tier": 0, "label": "first real run on CPU (smoke_20, 20 dev items)",
            "params": {"MODE": "first_run", "MODELS": ["gemma-3-1b-it"], "FORCED_CHOICE": True},
            "jobs": [{"run": "smoke_20", "models": ["gemma-3-1b-it"], "overrides": None, "tag": "cpu"}],
            "hours": [cpu["smoke_20"], cpu["smoke_20"]], "basis": "RL-2026-10-01-06 CPU benchmark, worst case"}]
    for m in pilot:
        s = CPU_PARAM_SCALE[m]
        hi = s * (cpu["smoke_20"] + cpu["pilot_t1_200"] + cpu["pilot_t1_200_forced_choice"] + cpu["pilot_xcopa_200"])
        out.append({"queue": "cpu", "tier": 0, "label": f"Gate 1 pilot on CPU: {m}",
                    "params": {"MODE": "pilot", "MODELS": [m], "FORCED_CHOICE": True},
                    "jobs": [{"run": r, "models": [m], "overrides": None, "tag": "cpu"}      # the CPU notebook's RUN_DIR_TAG
                             for r in ("smoke_20", "pilot_t1_200", "pilot_xcopa_200")],
                    "hours": [hi, hi], "basis": f"RL-2026-10-01-06 CPU benchmark x {s} (parameter ratio), worst case"})
    gp = [KRP.find_run(plan, r) for r in ("pilot_t1_200", "pilot_xcopa_200")]
    out.append({"queue": "gpu", "tier": 0, "label": "Gate 1 pilot on the T4 (the alternative to the CPU chunks; free quota "
                                                     "before the smoke week)",
                "params": {"SMOKE_RUN_IDS": [], "ALLOW_UNPINNED_REVISION": False},
                "jobs": [{"run": r["id"], "models": pilot, "overrides": None, "tag": None} for r in gp],
                "hours": [sum(r["estimate"]["low"] for r in gp), sum(r["estimate"]["high"] for r in gp)],
                "basis": "plan estimate"})
    sm, st = KRP.find_run(plan, "smoke_20"), KRP.find_run(plan, "smoke_20_tpu")
    t4 = [m for m in KRP.expand_models(sm, plan, mc) if HW_QUEUE.get(model_hw(m, mc)) == "gpu"]
    out.append({"queue": "gpu", "tier": 0, "label": "smoke week: every T4 / 2xT4 model on 20 dev items (panel freeze input)",
                "params": {"SMOKE_RUN_IDS": []},
                "jobs": [{"run": "smoke_20", "models": t4, "overrides": None, "tag": None}],
                "hours": [sm["estimate"]["low"], sm["estimate"]["high"]], "basis": "plan estimate"})
    out.append({"queue": "tpu", "tier": 0, "label": "smoke week: the TPU trio on 20 dev items",
                "params": {"SMOKE_RUN_IDS": []},
                "jobs": [{"run": "smoke_20_tpu", "models": KRP.expand_models(st, plan, mc), "overrides": None, "tag": None}],
                "hours": [st["estimate"]["low"], st["estimate"]["high"]], "basis": "plan estimate"})
    return out


def build_chunks(plan: dict | None = None, mc: dict | None = None) -> dict:
    plan = plan or KRP.load_plan()
    mc = mc or KRP.load_models()
    jobs, unscheduled = make_jobs(plan, mc)
    raw = tier0_chunks(plan, mc)
    for q in ("gpu", "tpu"):
        for js in pack(jobs, q, mc):
            raw.append({"queue": q, "tier": js[0]["tier"], "label": "models: " + ", ".join(dict.fromkeys(j["model"] for j in js)),
                        "params": {"SMOKE_RUN_IDS": []} if q == "tpu" else {},
                        "jobs": merge_jobs(js),
                        "hours": [sum(j["hours"][0] for j in js), sum(j["hours"][1] for j in js)],
                        "basis": "plan estimate, equal split per model; re-priced after the smoke week (DD 8.5)",
                        "unbooked_hours": [round(sum(j["hours"][i] for j in js if j["booked_on"].startswith("unbooked")), 2)
                                           for i in (0, 1)]})
    raw.sort(key=lambda c: (c["tier"], {"cpu": 0, "gpu": 1, "tpu": 2}[c["queue"]]))
    chunks = []
    for i, c in enumerate(raw, 1):
        cid = f"c{i:02d}_{c['queue']}_t{c['tier']}"
        keys = KRP.item_keys_for_runs(plan, list(dict.fromkeys(j["run"] for j in c["jobs"])))
        lo, hi = (round(x, 2) for x in c["hours"])
        ch = {"id": cid, "order": i, "queue": c["queue"], "tier": c["tier"], "tier_label": TIER_LABEL[c["tier"]],
              "window": WINDOW[c["tier"]], "label": c["label"], "base_notebook": QUEUE_NOTEBOOK[c["queue"]],
              "notebook": f"notebooks/chunks/{cid}.ipynb", "jobs": c["jobs"], "item_keys": keys,
              "hours": {"low": lo, "high": hi, "basis": c["basis"]},
              "quota_hours": ({"x1": [lo, hi], "x2": [round(2 * lo, 2), round(2 * hi, 2)]} if c["queue"] == "gpu"
                              else {"x1": [lo, hi]} if c["queue"] == "tpu" else {"x1": [0, 0]}),
              "params": c["params"]}
        if c.get("unbooked_hours") and any(c["unbooked_hours"]):
            ch["unbooked_hours"] = c["unbooked_hours"]
        chunks.append(ch)
    return {"version": 1, "generated_by": "scripts/plan_chunks.py", "run_plan": "configs/run_plan.yaml",
            "rules": {"order": "reverse of the pre-registered cut order (DD 7.1, DD 8.5); tiers in TIER_LABEL",
                      "estimate": "line estimate split equally over the line's models; plan estimate, not a measurement",
                      "session_cap_hours": SESSION_CAP_H, "session_overhead_hours_assumed": SESSION_OVERHEAD_H,
                      "first_of_family": first_of_family(plan, mc), "redundant": list(REDUNDANT),
                      "quota_readings": {"x1": "a 2xT4 session hour costs one quota hour",
                                         "x2": "a 2xT4 session hour costs two [UNCERTAIN: verify]"}},
            "tiers": TIER_LABEL, "not_chunked": NOT_CHUNKED, "unscheduled": unscheduled, "chunks": chunks}


# --------------------------------------------------------------------------------------------- notebooks
def _set_param(src: str, var: str, value, cid: str) -> str:
    text = pprint.pformat(value, width=100, sort_dicts=False)
    line = f"{var} = {text}   # chunk {cid} (scripts/plan_chunks.py)"
    pat = re.compile(rf"^{re.escape(var)} = .*$", re.MULTILINE)
    if pat.search(src):
        return pat.sub(lambda _m: line, src, count=1)
    return src.rstrip("\n") + "\n" + line + "\n"


def chunk_notebook(ch: dict) -> nbformat.NotebookNode:
    nb = copy.deepcopy(KBN.BUILDERS[ch["base_notebook"]]())
    i = next(k for k, c in enumerate(nb.cells) if c.cell_type == "code" and "# ---- parameters" in c.source)
    src = nb.cells[i].source
    params = dict(ch["params"])
    if ch["queue"] in ("gpu", "tpu"):
        params["JOBS"] = ch["jobs"]
        params["VERIFY_ITEM_KEYS"] = ch["item_keys"] + (["noilai_dev"] if ch["queue"] == "gpu" and "SMOKE_RUN_IDS" not in params else [])
        if ch["queue"] == "gpu":
            params["RUN_ID"] = ch["jobs"][0]["run"]
            params["MODELS"] = []
        else:
            params["RUN_IDS"] = list(dict.fromkeys(j["run"] for j in ch["jobs"]))
            params["MODELS"] = []
    else:
        params["RUN_IDS"] = [j["run"] for j in ch["jobs"]]
    params["RUN_LABEL"] = ch["id"]
    for var, value in params.items():
        src = _set_param(src, var, value, ch["id"])
    nb.cells[i].source = src
    q = ch["quota_hours"]
    cost = " / ".join(f"{k} {v[0]}–{v[1]} h" for k, v in q.items())
    lines = [f"# Compute chunk {ch['id']} (order {ch['order']}) — generated by `scripts/plan_chunks.py`; do not edit", "",
             (f"**Tier {ch['tier']}:** {ch['tier_label']}. **Window:** {ch['window']}. **Estimate:** "
              f"{ch['hours']['low']}–{ch['hours']['high']} h ({ch['hours']['basis']}); quota cost {cost} "
              "(the x1 / x2 readings of a 2xT4 hour: `docs/COMPUTE_PLAN.md`)."), "",
             "| run line | models | run-directory tag |", "|---|---|---|",
             *(f"| {j['run']} | {', '.join(j['models'])} | {j['tag'] or '—'} |" for j in ch["jobs"]), "",
             ("Resumable: every job runs `scripts/run_eval.py --resume`; outputs are pushed to the private runs dataset every "
              "`PUSH_EVERY_MINUTES` and after each model; `scripts/check_run.py` writes `stats.json` and `results_hashes.json` "
              "per run directory. If the session ends early, attach the runs dataset and run this notebook again: finished rows "
              "are skipped. The chunk is done when every job reports `ok`. Below is "
              f"`notebooks/{ch['base_notebook']}.ipynb` with its parameters cell preset (`JOBS`, `VERIFY_ITEM_KEYS`, `RUN_LABEL`).")]
    head = KBN.md("\n".join(lines))
    nb.cells.insert(0, head)
    nb.metadata["noilai"] = {**nb.metadata.get("noilai", {}), "chunk": ch["id"], "generator": "scripts/plan_chunks.py"}
    nbformat.validate(nb)
    return nb


# --------------------------------------------------------------------------------------------- tables
def tables(spec: dict) -> str:
    plan = KRP.load_plan()
    q = plan.get("quota", {})
    gpu_w, tpu_w = q.get("kaggle_gpu_hours_per_week"), q.get("kaggle_tpu_hours_per_week")
    rows = ["| # | chunk | queue | tier | what | est. h (low–high) | quota h x1 | quota h x2 |", "|---|---|---|---|---|---|---|---|"]
    for c in spec["chunks"]:
        x2 = c["quota_hours"].get("x2", c["quota_hours"]["x1"])
        rows.append(f"| {c['order']} | `{c['id']}` | {c['queue']} | {c['tier']} | {c['label']} | {c['hours']['low']}–{c['hours']['high']} "
                    f"| {c['quota_hours']['x1'][0]}–{c['quota_hours']['x1'][1]} | {x2[0]}–{x2[1]} |")
    out = ["**Chunks, in run order** (estimates: plan line estimates split equally per model; not measurements):", "", *rows, ""]
    tot = ["| queue | tier | chunks | est. h low | est. h high | + session overhead (assumed) |", "|---|---|---|---|---|---|"]
    for qn in ("cpu", "gpu", "tpu"):
        for t in range(6):
            cs = [c for c in spec["chunks"] if c["queue"] == qn and c["tier"] == t]
            if cs:
                lo, hi = sum(c["hours"]["low"] for c in cs), sum(c["hours"]["high"] for c in cs)
                tot.append(f"| {qn} | {t} | {len(cs)} | {lo:.1f} | {hi:.1f} | {hi + SESSION_OVERHEAD_H * len(cs):.1f} |")
    out += ["**Totals by queue and tier:**", "", *tot, ""]
    cap = ["| stage-2 commit | test-split weeks to 22 Nov | GPU quota h (x1) | GPU clock h (x2) | TPU h | GPU tiers 1-5 fit at x1 (high + overhead) | at x2 |",
           "|---|---|---|---|---|---|---|"]
    gpu_post = [c for c in spec["chunks"] if c["queue"] == "gpu" and c["tier"] >= 1]

    def reach(capacity: float, factor: int) -> str:
        used, last = 0.0, None
        for c in gpu_post:
            need = factor * (c["hours"]["high"] + SESSION_OVERHEAD_H)
            if used + need > capacity:
                break
            used += need
            last = c
        if last is None:
            return "none"
        if last is gpu_post[-1]:
            return "all (through tier 5)"
        return f"through order {last['order']} (tier {last['tier']})"

    for label, weeks in STAGE2_SCENARIOS:
        cap.append(f"| {label} | {weeks} | {gpu_w * weeks} | {gpu_w * weeks // 2} | {tpu_w * weeks} | {reach(gpu_w * weeks, 1)} | "
                   f"{reach(gpu_w * weeks, 2)} |")
    out += [(f"**Capacity between the stage-2 commit and the results freeze** (quota {gpu_w} GPU-h and {tpu_w} TPU-h a week, "
             "`configs/run_plan.yaml` `quota`, secondary sources [UNCERTAIN: verify in Kaggle's settings]; one account):"), "", *cap, ""]
    if spec["unscheduled"]:
        out += ["**Unscheduled (no zero-cost route):** " + "; ".join(f"`{u['run']}` × `{u['model']}` ({u['hours'][0]}–{u['hours'][1]} h)"
                                                                     for u in spec["unscheduled"]), ""]
    unb = [c for c in spec["chunks"] if c.get("unbooked_hours")]
    if unb:
        lo, hi = sum(c["unbooked_hours"][0] for c in unb), sum(c["unbooked_hours"][1] for c in unb)
        out += [(f"**Unbooked TPU time:** the TPU models' equal shares of gpu_hours lines, {lo:.1f}–{hi:.1f} TPU-h, are booked on "
                 "no line of `plan_lines` (the plan's `tpu_models_and_bf16` line covers only tpu_main, the TPU smoke, reasoning and "
                 "bf16 drift)."), ""]
    return "\n".join(out)


def render_yaml(spec: dict) -> str:
    import yaml
    head = ("# configs/compute_chunks.yaml -- GENERATED by scripts/plan_chunks.py from configs/run_plan.yaml and\n"
            "# configs/models.yaml; do not edit (change the rules in the script, then --write). docs/COMPUTE_PLAN.md\n"
            "# explains the order (reverse of the pre-registered cut order) and the estimates (plan estimates, equal split\n"
            "# per model, re-priced after the smoke week; none is a measurement).\n")
    return head + yaml.safe_dump(spec, sort_keys=False, allow_unicode=True, width=120)


def doc_with_block(doc: str, block: str) -> str:
    if BEGIN not in doc or END not in doc:
        raise SystemExit(f"{COMPUTE_PLAN} lacks the generated-block markers")
    a, rest = doc.split(BEGIN, 1)
    _, b = rest.split(END, 1)
    return a + BEGIN + "\n" + block + "\n" + END + b


def write(spec: dict) -> list[Path]:
    out = []
    CHUNKS_YAML.write_text(render_yaml(spec), encoding="utf-8")
    out.append(CHUNKS_YAML)
    CHUNK_DIR.mkdir(parents=True, exist_ok=True)
    keep = set()
    for ch in spec["chunks"]:
        p = ROOT / ch["notebook"]
        keep.add(p.name)
        nb = chunk_notebook(ch)
        if p.exists():
            old = nbformat.read(str(p), as_version=4)
            if KBN.sources(old) == KBN.sources(nb):
                continue
            ids = {(c.cell_type, c.source): c.get("id") for c in old.cells}
            for c in nb.cells:
                if ids.get((c.cell_type, c.source)):
                    c["id"] = ids[(c.cell_type, c.source)]
        nbformat.write(nb, str(p))
        out.append(p)
    for p in CHUNK_DIR.glob("*.ipynb"):
        if p.name not in keep:
            p.unlink()
            out.append(p)
    if COMPUTE_PLAN.exists():
        doc = COMPUTE_PLAN.read_text(encoding="utf-8")
        new = doc_with_block(doc, tables(spec))
        if new != doc:
            COMPUTE_PLAN.write_text(new, encoding="utf-8")
            out.append(COMPUTE_PLAN)
    return out


def check(spec: dict) -> list[str]:
    problems = []
    if not CHUNKS_YAML.exists() or CHUNKS_YAML.read_text(encoding="utf-8") != render_yaml(spec):
        problems.append(f"{CHUNKS_YAML.relative_to(ROOT)} differs from the generator")
    names = set()
    for ch in spec["chunks"]:
        p = ROOT / ch["notebook"]
        names.add(p.name)
        if not p.exists():
            problems.append(f"{ch['notebook']}: missing")
        elif KBN.sources(nbformat.read(str(p), as_version=4)) != KBN.sources(chunk_notebook(ch)):
            problems.append(f"{ch['notebook']}: cell sources differ from the generator")
    extra = sorted(p.name for p in CHUNK_DIR.glob("*.ipynb") if p.name not in names) if CHUNK_DIR.exists() else []
    problems += [f"notebooks/chunks/{n}: not a chunk of the plan" for n in extra]
    if COMPUTE_PLAN.exists():
        doc = COMPUTE_PLAN.read_text(encoding="utf-8")
        if doc_with_block(doc, tables(spec)) != doc:
            problems.append("docs/COMPUTE_PLAN.md: generated block differs")
    else:
        problems.append("docs/COMPUTE_PLAN.md: missing")
    return problems


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    g.add_argument("--table", action="store_true")
    args = ap.parse_args(argv)
    spec = build_chunks()
    if args.table:
        print(tables(spec))
        return 0
    if args.write:
        for p in write(spec):
            print("[write]", p.relative_to(ROOT))
        return 0
    probs = check(spec)
    for p in probs:
        print("[drift]", p)
    print("[ok   ] chunks match the generator" if not probs else f"[FAIL ] {len(probs)} problem(s); run --write")
    return 1 if probs else 0


if __name__ == "__main__":
    sys.exit(main())
