#!/usr/bin/env python
"""Appendix table of the tokenizer audit and census, from data/audit/counts.json and the audit files.

    python paper/gen_tokenizer_audit.py --counts data/audit/counts.json --audit-dir data/audit \
        --out paper/tables/tokenizer_audit.tex
    python paper/gen_tokenizer_audit.py ... --check      # exit 1 if the committed table is stale

One row per (tokenizer, encoding): tokens per syllable, single-token share, boundary alignment
over all syllables and among split syllables (with the number of split syllables), the share of
syllables split at the onset|rime seam, the share whose tone mark is a token of its own (NFD),
and, per tokenizer, the census verdicts and the share of census strings whose NFD (PC) ids are
identical to NFC and whose NFD (PC) sequence is longer. Every number is read from
`counts.json` (`tokenizer_audit.<name>.summary`, written by scripts/reconcile_counts.py) and
from `<name>.json` (`normalization_census`, written by scripts/audit_tokenizers.py); nothing is
typed (DESIGN_DECISIONS 12.43). Numbers in the prose of Section 4 are the same values, rounded
the same way, and tests/test_paper.py holds them to the files.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from pathlib import Path

DISPLAY = {"gemma3": "Gemma 3 (262,144 pieces)", "gemma2": "Gemma 2 (256,000 pieces)"}
ORDER = ("gemma3", "gemma2")
ENC = (("nfc", "NFC"), ("nfd", "NFD"))


def pct(x: float, digits: int = 1) -> str:
    return f"{100 * x:.{digits}f}"


def rows(counts: dict, audit_dir: Path) -> tuple[list[str], dict]:
    out, side = [], {}
    audit = counts["tokenizer_audit"]
    names = [n for n in ORDER if n in audit] + sorted(n for n in audit if n not in ORDER)
    for name in names:
        summ = audit[name]["summary"]
        census = json.loads((audit_dir / f"{name}.json").read_text(encoding="utf-8")).get("normalization_census", {})
        side[name] = {"summary": summ, "census": {k: census.get(k) for k in (
            "n_samples", "verdict_nfd", "verdict_pc", "nfd_same_ids_frac", "nfd_longer_frac", "pc_same_ids_frac", "pc_longer_frac",
            "nfd_roundtrip_ok_frac", "pc_roundtrip_ok_frac")}}
        label = DISPLAY.get(name, name)
        for i, (key, enc) in enumerate(ENC):
            s = summ[key]
            first = f"\\multirow{{2}}{{*}}{{{label}}}" if i == 0 else ""
            tone = pct(s["tone_isolated_frac"]) if s["tone_isolated_frac"] else "0.0"
            out.append(
                f"{first} & {enc} & {s['tokens_per_syllable_mean']:.2f} & {pct(s['single_token_frac'])} & "
                f"{s['boundary_alignment_mean']:.2f} & {s['boundary_alignment_among_split_mean']:.3f} ({int(s['n_split']):,}) & "
                f"{pct(s['onset_rime_split_frac'])} & {tone} \\\\"
            )
    return out, side


def census_lines(side: dict) -> list[str]:
    lines = []
    for name, d in side.items():
        c = d["census"]
        if not c.get("verdict_nfd"):
            continue
        lines.append(
            f"{DISPLAY.get(name, name)}: NFD {c['verdict_nfd'].replace('_', ' ')} (identical ids {pct(c['nfd_same_ids_frac'])}\\%, "
            f"longer {pct(c['nfd_longer_frac'])}\\%, round trip {pct(c['nfd_roundtrip_ok_frac'], 0)}\\%); "
            f"PC {c['verdict_pc'].replace('_', ' ')} (identical {pct(c['pc_same_ids_frac'])}\\%, longer {pct(c['pc_longer_frac'])}\\%, "
            f"round trip {pct(c['pc_roundtrip_ok_frac'], 0)}\\%)"
        )
    return lines


def table(counts: dict, audit_dir: Path, src: str, stamp: str) -> tuple[str, dict]:
    body, side = rows(counts, audit_dir)
    census = census_lines(side)
    n_census = next((d["census"].get("n_samples") for d in side.values() if d["census"].get("n_samples")), None)
    tex = [f"% GENERATED by paper/gen_tokenizer_audit.py from {src} on {stamp}; do not edit by hand.",
           "\\begin{table*}[t]\\centering\\footnotesize\\setlength{\\tabcolsep}{4pt}",   # eight columns overflow at 6pt
           "\\begin{tabular}{@{}llrrrrrr@{}}",
           "\\toprule",
           "Tokenizer & Enc. & Tok./syll. & Single (\\%) & Align. all & Align. split ($n$) & Onset$|$rime (\\%) & Tone isol.\\ (\\%) \\\\",
           "\\midrule"]
    tex += body
    tex += ["\\bottomrule", "\\end{tabular}",
            "\\caption{Tokenizer audit over the 6,595 standard syllables in running-text position (preceded by a space). "
            "Tok./syll.: mean tokens per syllable; Single: share of single-token syllables; Align.\\ all: boundary alignment "
            "with a single-token syllable counted as 1.0; Align.\\ split: alignment among split syllables, with their number; "
            "Onset$|$rime: share of syllables with a token boundary exactly at the onset--rime seam; Tone isolated: share whose "
            "tone mark is a token of its own (NFD only). "
            f"Census on the fixed {n_census:,}-string probe set (500 multi-syllable words and 500 \\noilai{{}} inputs): "
            + "; ".join(census) + ". "
            "\\placeholder{Every panel tokenizer, with its census verdict per engine, after the freeze.}}",
            "\\label{tab:tokaudit}",
            "\\end{table*}"]
    return "\n".join(tex) + "\n", side


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--counts", default="data/audit/counts.json")
    ap.add_argument("--audit-dir", default="data/audit")
    ap.add_argument("--out", default="paper/tables/tokenizer_audit.tex")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    counts = json.loads(Path(a.counts).read_text(encoding="utf-8"))
    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%MZ")
    tex, side = table(counts, Path(a.audit_dir), a.counts, stamp)
    out = Path(a.out)

    def body(s: str) -> list[str]:
        return [ln for ln in s.splitlines() if not ln.startswith("% GENERATED")]

    if a.check:
        if not out.exists() or body(out.read_text(encoding="utf-8")) != body(tex):
            print("stale:", out)
            return 1
        print("tokenizer audit table current")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(tex, encoding="utf-8")
    out.with_suffix(".json").write_text(json.dumps(side, ensure_ascii=False, indent=1, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({"out": str(out), "tokenizers": list(side)}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
