#!/usr/bin/env python
"""Table 1 of the paper: item counts by task x variant x split, from a build manifest.

    python paper/gen_table1.py --manifest data/release/v0.2/manifest.json \
        --attested data/release/v0.2/attested.jsonl --out paper/tables/table1_counts.tex

The manifest is the one `scripts/build_data.py` writes next to the item files
(docs/DATA_FORMAT.md). Nothing in the emitted table is typed by hand: every number is
read from the manifest (or counted in the attested file), and the header comment names
the manifest, its git commit and seed. A build whose generator arguments differ from the
plan's defaults (1,500 + 1,000 base pairs, 1,000 / 500 / 500 items per cell, core 125)
is a smoke build, and the table says so in a red \\placeholder in its caption and in a
"smoke build; regenerate" comment, so that a skeleton table can never be mistaken for
the paper's data.

The smoke decision is made from the generator arguments (plus an explicit --smoke); a
build whose arguments match the plan but that holds fewer than ~10,000 items (a filter
left a cell short) is marked smoke by the size heuristic UNLESS --release declares it the
frozen release. The header comment records which rule decided. --note adds a red
\\placeholder note to the header and the caption (e.g. "v0.2 counts; superseded by the
v0.3 rebuild"), for a full-size build that is not (yet) the paper's data.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from collections import OrderedDict
from pathlib import Path

TASKS = ("T1", "T2", "T3")
VARIANTS = ("V1", "V2", "V3", "V4")
TASK_NAMES = {"T1": "transformation", "T2": "decoding", "T3": "validity"}

# Generator defaults of the founding plan (docs/PLAN_2026-09-30.md, section 2.3), as
# scripts/build_data.py encodes them.
PLAN_DEFAULTS = {"n_lexicon": 1500, "n_pseudo": 1000, "per_cell_t1": 1000, "per_cell_t2": 500,
                 "per_cell_t3": 500, "core_per_cell": 125}
SMOKE_MARK = "smoke build; regenerate"


def smoke_decision(manifest: dict, force: bool = False, release: bool = False) -> tuple[bool, str]:
    """(is_smoke, reason). A build is a smoke build when told so (--smoke), when a generator
    argument differs from the plan's defaults, or, unless --release declares it the frozen
    release, when it holds fewer than the plan's ~10,000 items."""
    if force:
        return True, "forced by --smoke"
    args = manifest.get("generator_args") or {}
    differing = {k: (args[k], v) for k, v in PLAN_DEFAULTS.items() if k in args and args[k] != v}
    if differing:
        return True, "generator arguments differ from the plan's defaults: " + ", ".join(
            f"{k}={a} (plan {b})" for k, (a, b) in sorted(differing.items()))
    n = int(manifest.get("n_items", 0))
    if release:
        return False, f"generator arguments match the plan; declared the frozen release by --release ({n:,} items)"
    if n < 10000:
        return True, f"generator arguments match the plan but the build holds {n:,} items (< 10,000); pass --release for the frozen release"
    return False, f"generator arguments match the plan; {n:,} items"


def is_smoke(manifest: dict, force: bool = False, release: bool = False) -> bool:
    return smoke_decision(manifest, force, release)[0]


def count_attested(path: Path | None) -> tuple[int | None, int | None]:
    """(rows, rows flagged vulgar) of a release attested.jsonl, or (None, None)."""
    if path is None or not path.exists():
        return None, None
    n = 0
    vulgar = 0
    with open(path, encoding="utf-8") as f:
        for ln in f:
            if not ln.strip():
                continue
            n += 1
            row = json.loads(ln)
            if str(row.get("vulgar", "no")).lower() in ("yes", "true", "1"):
                vulgar += 1
    return n, vulgar


def cell_counts(manifest: dict) -> OrderedDict:
    counts = manifest.get("counts", {})
    core = manifest.get("core_counts", {})
    pools = manifest.get("cell_pool_sizes", {})
    out: OrderedDict = OrderedDict()
    for t in TASKS:
        for v in VARIANTS:
            dev = int(counts.get(f"{t}-{v}-dev", 0))
            test = int(counts.get(f"{t}-{v}-test", 0))
            out[(t, v)] = {"dev": dev, "test": test, "core": int(core.get(f"{t}-{v}", 0)),
                           "total": dev + test, "pool": pools.get(f"{t}-{v}")}
    return out


def render(manifest: dict, manifest_path: str, attested: tuple[int | None, int | None],
           smoke: bool, now: str, reason: str = "", note: str | None = None) -> str:
    cells = cell_counts(manifest)
    commit = str(manifest.get("git_commit", "unknown"))[:12]
    dirty = " (dirty tree)" if manifest.get("git_dirty") else ""
    seed = manifest.get("seed", "?")
    lines = []
    lines.append("% GENERATED by paper/gen_table1.py -- do not edit by hand.")
    lines.append(f"% source manifest: {manifest_path}")
    lines.append(f"% generator commit {commit}{dirty}, seed {seed}, generated {now}")
    lines.append(f"% smoke decision: {reason}")
    if smoke:
        lines.append(f"% {SMOKE_MARK}: generator arguments differ from the plan's defaults or the build "
                     "is smaller than the paper's ~10,000 items. Re-run this script on the frozen release.")
    if note:
        lines.append(f"% note: {note}")
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering\small")
    lines.append(r"\begin{tabular}{@{}llrrrrr@{}}")
    lines.append(r"\toprule")
    lines.append(r"Task & Variant & Dev & Test & Core & Total & Pool \\")
    lines.append(r"\midrule")
    grand = {"dev": 0, "test": 0, "core": 0, "total": 0}
    for t in TASKS:
        sub = {"dev": 0, "test": 0, "core": 0, "total": 0}
        for i, v in enumerate(VARIANTS):
            c = cells[(t, v)]
            pool = "--" if c["pool"] is None else f"{c['pool']:,}"
            first = rf"\multirow{{{len(VARIANTS) + 1}}}{{*}}{{\task{{{t}}} {TASK_NAMES[t]}}}" if i == 0 else ""
            lines.append(f"{first} & \\var{{{v[1]}}} & {c['dev']:,} & {c['test']:,} & {c['core']:,} & {c['total']:,} & {pool} \\\\")
            for k in sub:
                sub[k] += c[k]
        lines.append(f" & all & {sub['dev']:,} & {sub['test']:,} & {sub['core']:,} & {sub['total']:,} & \\\\")
        lines.append(r"\midrule")
        for k in grand:
            grand[k] += sub[k]
    lines.append(f"Generated & & {grand['dev']:,} & {grand['test']:,} & {grand['core']:,} & {grand['total']:,} & \\\\")
    n_att, n_vulgar = attested
    if n_att is None:
        att_cell = r"\placeholder{200--400}"
        vul_cell = r"\placeholder{TODO}"
    else:
        att_cell = f"{n_att:,}"
        vul_cell = f"{n_vulgar:,}"
    lines.append(f"Attested & & -- & {att_cell} & -- & {att_cell} & \\\\")
    lines.append(f"\\quad of which flagged vulgar & & & {vul_cell} & & & \\\\")
    lines.append(r"\midrule")
    lines.append(r"Base pairs & & \multicolumn{5}{l}{" + f"{int(manifest.get('n_base_pairs', 0)):,} (split by pair; dev fraction "
                 f"{(manifest.get('generator_args') or {}).get('dev_frac', 0.2)})" + r"} \\")
    lines.append(r"Validation $\alpha$ & & \multicolumn{5}{l}{\placeholder{$\alpha$ = TODO, 95\% CI TODO; 1,000 items, 200 triple-judged}} \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    smoke_note = (r" \placeholder{" + SMOKE_MARK + r": these counts come from a reduced build "
                  f"({int(manifest.get('n_items', 0)):,} items, seed {seed}); the frozen release replaces them.}}") if smoke else ""
    if note:
        smoke_note += r" \placeholder{" + note + "}"
    lines.append(r"\caption{\noilai{} item counts by task, variant and split. Core is the balanced subset of the "
                 r"test split that API-served models see (\task{T3}: yes/no pairs kept together). Pool is the "
                 r"number of legal, non-identity items available per cell before capping (\task{T1}, \task{T2}); "
                 r"the drop rate follows from it. Attested examples are folk and literary "
                 r"\vi{n\'{o}i l\'{a}i}; items flagged vulgar never reach an API or the human-baseline form."
                 + smoke_note + "}")
    lines.append(r"\label{tab:counts}")
    lines.append(r"\end{table}")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--manifest", type=Path, required=True)
    ap.add_argument("--attested", type=Path, default=None, help="release attested.jsonl (optional)")
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--smoke", action="store_true", help="force the smoke-build marking")
    ap.add_argument("--release", action="store_true",
                    help="the frozen release: bypass the size heuristic (generator arguments must still match the plan)")
    ap.add_argument("--note", default=None,
                    help="a red \\placeholder note added to the header and the caption (plain text, no braces)")
    args = ap.parse_args(argv)
    if args.smoke and args.release:
        ap.error("--smoke and --release contradict each other")
    if args.note and any(ch in args.note for ch in "{}\\"):
        ap.error("--note is plain text: no braces or backslashes")
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    smoke, reason = smoke_decision(manifest, force=args.smoke, release=args.release)
    now = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%MZ")
    tex = render(manifest, str(args.manifest), count_attested(args.attested), smoke, now, reason, args.note)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(tex, encoding="utf-8")
    print(json.dumps({"out": str(args.out), "n_items": manifest.get("n_items"), "smoke": smoke, "reason": reason,
                      "note": args.note}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
