#!/usr/bin/env python
"""Appendix rule tables, generated from the parser's constants and the Hunspell lists.

    python paper/gen_rule_tables.py --out paper/tables

Writes
  rules_components.tex   the canonical symbol inventory (onsets, nuclei, codas, tones)
                         from noilai.vi.syllable / noilai.vi.unicode constants
  rules_onsets.tex       surface spelling of every canonical onset, with the c/k/q, g/gh,
                         ng/ngh triggers and the gi contraction, each example SPELLED BY
                         THE ENGINE (noilai.vi.syllable.spell); the plain rows take their
                         two examples from the ATTESTED inventory (noilai.vi.lexicon.
                         load_inventory), so that no row shows an engine-legal non-word
  rules_spelling.tex     the remaining spelling rules (glide letter, i/y, short a, coda
                         letters, stop-coda tones, open/closed nuclei, tone-mark placement)
                         with engine examples, plus the i/y EMISSION rule of the release
                         (noilai.vi.lexicon.emit), whose examples are computed by emit()
                         next to the speller's default so that the two cannot be confused
  rules_placement.tex    the 69 syllables whose tone-mark letter differs between the old
                         and the new placement convention: the set difference of the two
                         Hunspell lists, each pair checked against the engine's rule
  rules_variants.tex     the six noi lai variants (V1-V4 generated cells, V5-V6 taxonomy
                         rows) with the components they move and an engine-computed
                         example per variant

Every example is computed, never typed, so the tables cannot drift from the code. The
placement table needs data/external/vi-DauMoi.dic and vi-DauCu.dic (scripts/fetch_resources.py).
Vietnamese glosses are marked for native validation in the paper text, not here.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from noilai.gen import variants as V
from noilai.vi import lexicon as L
from noilai.vi import unicode as U
from noilai.vi.syllable import (
    CANONICAL_ONSETS,
    CLOSED_ONLY_NUCLEI,
    CODAS,
    NUCLEI,
    ONSET_SPELLINGS,
    OPEN_ONLY_NUCLEI,
    STOP_CODAS,
    Syllable,
    spell,
    try_parse,
)

EXPECTED_PLACEMENT_PAIRS = 69


def _hdr(name: str, now: str) -> str:
    return (f"% GENERATED by paper/gen_rule_tables.py ({name}) from noilai.vi.syllable constants "
            f"and the Hunspell lists; generated {now}. Do not edit by hand.\n")


def _tex(s: str) -> str:
    """Escape the few LaTeX specials that can occur in a spelling or a symbol."""
    return (s.replace("\\", r"\textbackslash{}").replace("&", r"\&").replace("%", r"\%")
            .replace("#", r"\#").replace("_", r"\_").replace("$", r"\$"))


def _sym(s: str) -> str:
    return r"\texttt{" + (_tex(s) if s else r"$\varnothing$") + "}"


# ------------------------------------------------------------------ components
def components_table(now: str) -> str:
    lines = [_hdr("components", now)]
    lines.append(r"\begin{table*}[t]\centering\small")
    lines.append(r"\begin{tabular}{@{}lp{0.78\textwidth}@{}}")
    lines.append(r"\toprule")
    lines.append(r"Slot & Canonical symbols (as the parser writes them) \\")
    lines.append(r"\midrule")
    onsets = ", ".join(_sym(o) for o in CANONICAL_ONSETS)
    lines.append(rf"Onset ({len(CANONICAL_ONSETS)}) & {onsets}. "
                 r"\texttt{c} stands for /k/ however spelled (c, k, q); \texttt{g} for the voiced velar fricative "
                 r"however spelled (g, gh); \texttt{ng} for the velar nasal however spelled (ng, ngh); "
                 r"\texttt{gi} is the onset that contracts a following i; "
                 r"\texttt{p} occurs only in loanwords. \\")
    lines.append(r"Glide & present or absent (written \texttt{u} or \texttt{o}; the \texttt{u} of \texttt{qu} is the glide). \\")
    nuclei = ", ".join(_sym(n) for n in NUCLEI)
    lines.append(rf"Nucleus ({len(NUCLEI)}) & {nuclei}. Open-only (never take a coda): "
                 + ", ".join(_sym(n) for n in sorted(OPEN_ONLY_NUCLEI)) + r". Closed-only (always take a coda): "
                 + ", ".join(_sym(n) for n in sorted(CLOSED_ONLY_NUCLEI)) + r". \\")
    codas = ", ".join(_sym(c) for c in CODAS)
    lines.append(rf"Coda ({len(CODAS)}) & {codas}. \texttt{{j}} is the semivowel written i/y, \texttt{{w}} the semivowel "
                 r"written o/u; the stop codas " + ", ".join(_sym(c) for c in sorted(STOP_CODAS))
                 + r" take only the tones sắc and nặng. \\")
    tones = ", ".join(f"{i}~=~{_tex(vi)}" for i, vi in enumerate(U.TONE_NAMES_VI))
    lines.append(rf"Tone (6) & {tones}; index 0 (ngang) is the unmarked level tone, the other five carry a diacritic. \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\caption{The parser's canonical symbols (\texttt{noilai.vi.syllable}). A syllable is onset + rime + tone, "
                 r"the rime being glide$^?$ + nucleus + coda$^?$. Legality is decided against the attested inventory "
                 r"(Hunspell vi\_VN, both placement styles, extended with word-list syllables that reuse an attested rime).}")
    lines.append(r"\label{tab:components}")
    lines.append(r"\end{table*}")
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ onsets
def _ex(onset: str, glide: bool, nucleus: str, coda: str = "", tone: int = 0) -> str:
    return spell(Syllable(onset=onset, glide=glide, nucleus=nucleus, coda=coda, tone=tone))


# (glide, nucleus, coda, tone) templates tried in order for the attested onset examples
ONSET_EXAMPLE_TEMPLATES = [
    (False, "a", "", 0), (False, "ô", "ng", 1), (False, "a", "ng", 0), (False, "i", "n", 0), (False, "ê", "n", 0),
    (False, "o", "n", 0), (False, "u", "ng", 0), (False, "a", "m", 0), (False, "i", "nh", 0), (False, "ư", "", 0),
    (False, "e", "", 0), (False, "ô", "", 0), (False, "â", "n", 2), (False, "a", "n", 2), (False, "i", "", 0),
    (False, "i", "p", 2), (False, "e", "p", 2), (False, "o", "", 2), (False, "u", "", 0), (False, "ê", "", 0),
]


def attested_examples(onset: str, n: int = 2) -> list[str]:
    """The first `n` ONSET_EXAMPLE_TEMPLATES that are attested syllables (exact syllable,
    tone included, in the release inventory), spelled by the engine. Fails loudly when
    the templates do not cover an onset, so that no table row falls back to a non-word."""
    inv = L.load_inventory()
    out = []
    for glide, nucleus, coda, tone in ONSET_EXAMPLE_TEMPLATES:
        syl = Syllable(onset=onset, glide=glide, nucleus=nucleus, coda=coda, tone=tone)
        if inv.is_attested(syl):
            out.append(spell(syl))
        if len(out) == n:
            return out
    raise SystemExit(f"fewer than {n} attested example syllables for onset {onset!r}; extend ONSET_EXAMPLE_TEMPLATES")


def onsets_table(now: str) -> str:
    # surface spellings per canonical onset, from the parser's spelling map
    surfaces: dict[str, list[str]] = {}
    for sp, canon in ONSET_SPELLINGS.items():
        surfaces.setdefault(canon, []).append(sp)
    lines = [_hdr("onsets", now)]
    lines.append(r"\begin{table}[t]\centering\small")
    lines.append(r"\begin{tabular}{@{}lll@{}}")
    lines.append(r"\toprule")
    lines.append(r"Onset & Written & Engine examples \\")
    lines.append(r"\midrule")
    for o in CANONICAL_ONSETS:
        if o == "":
            lines.append(rf"{_sym('')} & (nothing) & {_ex('', False, 'a')}, {_ex('', False, 'iê', 'n', 0)}, {_ex('', False, 'i', '', 2)} \\")
            continue
        written = ", ".join(sorted(surfaces.get(o, [o]), key=len))
        if o == "c":
            ex = f"{_ex('c', False, 'a')} / {_ex('c', False, 'e')} / {_ex('c', True, 'a')} (c before a, k before e \\^{{e}} i, q before the glide)"
        elif o == "g":
            ex = f"{_ex('g', False, 'a')} / {_ex('g', False, 'e')} (gh before e \\^{{e}} i)"
        elif o == "ng":
            ex = f"{_ex('ng', False, 'a')} / {_ex('ng', False, 'e')} / {_ex('ng', True, 'e')} (ngh before e \\^{{e}} i; not with a glide)"
        elif o == "gi":
            ex = f"{_ex('gi', False, 'a')} / {_ex('gi', False, 'i', '', 1)} / {_ex('gi', False, 'iê', 'ng')} (the rime's initial i is absorbed)"
        else:
            ex = ", ".join(attested_examples(o))
        lines.append(rf"{_sym(o)} & \texttt{{{_tex(written)}}} & {ex} \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\caption{Surface spelling of the canonical onsets. The k/gh/ngh spellings are triggered by the first "
                 r"\emph{written} letter after the onset (e, \^{e}, i), so a glide switches them off (\texttt{ngoe}, "
                 r"\texttt{nguy}); every example is produced by \texttt{noilai.vi.syllable.spell}, and the examples of "
                 r"the plain rows are attested syllables of the release inventory.}")
    lines.append(r"\label{tab:onsets}")
    lines.append(r"\end{table}")
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ spelling rules
IY_EXAMPLE_WORDS = ("lí", "kĩ", "mĩ", "sĩ", "tỉ")


def _iy_emission_examples() -> str:
    """`emit(x)` next to `spell(x)` for the i/y example syllables, both computed, so that the
    released form and the speller's default are shown side by side and cannot be confused."""
    sylls = [try_parse(w, strict=False).syllable for w in IY_EXAMPLE_WORDS]
    emitted = ", ".join(L.emit(x) for x in sylls)
    default = ", ".join(spell(x) for x in sylls)
    return f"{emitted} (speller: {default})"


def spelling_table(now: str) -> str:
    rows = [
        ("Glide letter", "\\texttt{u} after q and before \\^{a} \\^{e} \\horn{o} \\^{o} i ia i\\^{e}; \\texttt{o} before a \\u{a} e",
         f"{_ex('h', True, 'a')}, {_ex('h', True, 'e')}, {_ex('h', True, 'ê')}, {_ex('t', True, 'â', 'n')}, {_ex('c', True, 'a')}"),
        ("Nucleus i (speller default)", "written \\texttt{y} after the glide and in the bare syllable; \\texttt{i} elsewhere; "
         "the canonical form for parsing and scoring, where i and y are equivalent in these contexts",
         f"{_ex('c', True, 'i')}, {_ex('', False, 'i', '', 2)}, {_ex('l', False, 'i', '', 2)}, {_ex('m', False, 'i', 'nh')}"),
        ("i/y emission (release)", "a bare /i/ after a consonant onset is released in the syllable's majority spelling "
         "in the reference corpus (fallback: the word list), never \\texttt{y} after s or v; a zero-onset bare /i/ takes "
         "the lexicon form per tone (\\texttt{noilai.vi.lexicon.emit})",
         _iy_emission_examples()),
        ("Nucleus ia / i\\^{e}", "ya / y\\^{e} after the glide; y\\^{e} with a zero onset",
         f"{_ex('kh', True, 'ia')}, {_ex('c', True, 'iê', 'n')}, {_ex('', False, 'iê', 'w')}, {_ex('t', False, 'iê', 'ng', 2)}"),
        ("Short \\u{a}", "written \\texttt{a} before the semivowel codas",
         f"{_ex('t', False, 'ă', 'j')} vs.\\ {_ex('t', False, 'a', 'j')}; {_ex('t', False, 'ă', 'w')} vs.\\ {_ex('t', False, 'a', 'w')}"),
        ("Coda /j/", "\\texttt{y} after \\u{a} \\^{a}, \\texttt{i} elsewhere",
         f"{_ex('m', False, 'â', 'j')}, {_ex('m', False, 'a', 'j')}, {_ex('m', False, 'ô', 'j')}"),
        ("Coda /w/", "\\texttt{o} after a e, \\texttt{u} elsewhere",
         f"{_ex('ch', False, 'a', 'w')}, {_ex('c', False, 'e', 'w')}, {_ex('m', False, 'ư', 'w')}, {_ex('ch', False, 'iê', 'w')}"),
        ("Stop codas", "p t c ch take only sắc and nặng",
         f"{_ex('m', False, 'â', 't', 5)}, {_ex('b', False, 'â', 't', 2)}; *{U.strip_tones(_ex('m', False, 'â', 't', 5))} is rejected by the inventory"),
        ("Open-only nuclei", "ia ua \\horn{u}a never take a coda", f"{_ex('m', False, 'ia', '', 2)}, {_ex('m', False, 'ua', '', 1)}"),
        ("Closed-only nuclei", "i\\^{e} u\\^{o} \\horn{u}\\horn{o} \\u{a} \\^{a} always take a coda", f"{_ex('m', False, 'uô', 'n', 2)}, {_ex('m', False, 'ươ', 'n', 5)}"),
        ("Tone mark, new style", "on the nucleus letter (second letter of i\\^{e} y\\^{e} u\\^{o} \\horn{u}\\horn{o}, first of ia ua \\horn{u}a)",
         f"{_ex('t', False, 'iê', 'ng', 2)}, {_ex('m', False, 'uô', 'n', 2)}, {_ex('m', False, 'ia', '', 2)}"),
        ("Tone mark, old style", "differs only on open oa oe uy after a non-q onset (mark on the first vowel letter)",
         f"{spell(Syllable('h', True, 'a', '', 1), 'new')} / {spell(Syllable('h', True, 'a', '', 1), 'old')}, "
         f"{spell(Syllable('kh', True, 'e', '', 3), 'new')} / {spell(Syllable('kh', True, 'e', '', 3), 'old')}, "
         f"{spell(Syllable('th', True, 'i', '', 3), 'new')} / {spell(Syllable('th', True, 'i', '', 3), 'old')}"),
    ]
    lines = [_hdr("spelling", now)]
    lines.append(r"\begin{table*}[t]\centering\small")
    lines.append(r"\begin{tabular}{@{}lp{0.42\textwidth}p{0.36\textwidth}@{}}")
    lines.append(r"\toprule")
    lines.append(r"Rule & Statement & Engine examples \\")
    lines.append(r"\midrule")
    for name, stmt, ex in rows:
        lines.append(rf"{name} & {stmt} & {ex} \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\caption{Spelling rules of the speller (\texttt{noilai.vi.syllable.spell}), with examples spelled by the "
                 r"engine. Released items are written through \texttt{noilai.vi.lexicon.emit}, which applies the same rules "
                 r"and then the i/y emission row, so the released i/y form can differ from the speller's default. The same "
                 r"rules, run in reverse, are the parser's spelling round-trip: a syllable whose standard spelling does not "
                 r"reproduce the input is rejected in strict mode (so \vi{c\'{e}o} for \vi{k\'{e}o} scores as a spelling error, "
                 r"never as correct).}")
    lines.append(r"\label{tab:spelling}")
    lines.append(r"\end{table*}")
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ placement pairs
def placement_pairs() -> list[tuple[str, str]]:
    """(new-style, old-style) spellings that differ between the two Hunspell lists.

    The two files hold the same syllables (6,611 lowercase entries each); exactly the
    entries present in one list and absent from the other are the ones whose tone-mark
    letter moves. Each new-only entry is mapped to its old-style spelling by the engine's
    own rule and must land in the old-only set; a mismatch is a bug in either the rule
    or the resource and stops the script."""
    new = set(L.load_hunspell_syllables("new"))
    old = set(L.load_hunspell_syllables("old"))
    only_new = sorted(new - old)
    only_old = old - new
    pairs = []
    for n in only_new:
        p = try_parse(n)
        if p is None:
            raise SystemExit(f"new-only Hunspell syllable does not parse: {n!r}")
        o = spell(p.syllable, style="old")
        if o not in only_old:
            raise SystemExit(f"rule maps {n!r} to {o!r}, which is not an old-only Hunspell entry")
        pairs.append((n, o))
    if len(pairs) != len(only_old):
        raise SystemExit(f"{len(pairs)} new-only vs {len(only_old)} old-only entries")
    return pairs


def placement_table(now: str, pairs: list[tuple[str, str]], ncol: int = 3) -> str:
    lines = [_hdr("placement", now)]
    lines.append(f"% {len(pairs)} pairs (new style, old style)")
    lines.append(r"\begin{table}[t]\centering\small")
    lines.append(r"\begin{tabular}{@{}" + "ll" * ncol + "@{}}")
    lines.append(r"\toprule")
    lines.append(" & ".join(["New & Old"] * ncol) + r" \\")
    lines.append(r"\midrule")
    nrow = -(-len(pairs) // ncol)
    for r in range(nrow):
        cells = []
        for c in range(ncol):
            i = c * nrow + r
            if i < len(pairs):
                cells.append(f"{pairs[i][0]} & {pairs[i][1]}")
            else:
                cells.append(" & ")
        lines.append(" & ".join(cells) + r" \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(rf"\caption{{The {len(pairs)} syllables of the Hunspell vi\_VN list whose tone-mark letter differs between "
                 r"the new placement convention (mark on the nucleus letter) and the old one (mark on the first vowel letter "
                 r"of the open rimes oa, oe, uy). The set is the difference between the two released lists, and the engine's "
                 r"rule reproduces every pair; the C2 arm converts running text between the two conventions and changes "
                 r"exactly these syllables (and their capitalized forms).}")
    lines.append(r"\label{tab:placement}")
    lines.append(r"\end{table}")
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ variants
VARIANT_EXAMPLES = {"V1": ("mèo", "cái"), "V2": ("đầu", "tiên"), "V3": ("bí", "mật"), "V4": ("bí", "mật"),
                    "V5": ("giải", "pháp"), "V6": ("mèo", "cái")}
# attested outputs the engine must reproduce (data/attested_seed.tsv; V5 from DESIGN_DECISIONS 3.6);
# a mismatch stops the script. V6 has no attested example: it is V1 read in the other order.
VARIANT_ATTESTED = {"V1": "mài kéo", "V2": "tiền đâu", "V3": "bị mất", "V4": "bật mí", "V5": "phải giáp"}


def variants_table(now: str) -> str:
    all_variants = getattr(V, "ALL_VARIANTS", V.VARIANTS)
    generated = set(V.VARIANTS)
    lines = [_hdr("variants", now)]
    lines.append(r"\begin{table}[t]\centering\small")
    lines.append(r"\begin{tabular}{@{}lllll@{}}")
    lines.append(r"\toprule")
    lines.append(r"Variant & Swapped & Kept in place & Engine example & Status \\")
    lines.append(r"\midrule")
    all_parts = ["onset", "rime", "tone"]
    for v in all_variants:
        if v not in VARIANT_EXAMPLES:
            continue
        moved = ", ".join(p for p in all_parts if p in V.MOVES[v])
        kept = ", ".join(p for p in all_parts if p not in V.MOVES[v])
        a, b = (try_parse(s).syllable for s in VARIANT_EXAMPLES[v])
        x, y = V.apply(v, a, b)
        out = f"{spell(x)} {spell(y)}"
        if v in VARIANT_ATTESTED and out != VARIANT_ATTESTED[v]:
            raise SystemExit(f"{v}: engine gives {out!r}, attested {VARIANT_ATTESTED[v]!r}")
        status = "generated cell" if v in generated else r"taxonomy; \task{T2} gold; \task{T3} twins"
        lines.append(rf"\var{{{v[1]}}} & {moved} & {kept} & \vi{{{' '.join(VARIANT_EXAMPLES[v])}}} $\rightarrow$ \vi{{{out}}} & {status} \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\caption{The six \vi{nói lái} variants as component permutations of a syllable pair "
                 r"(\texttt{noilai.gen.variants}): the non-empty proper subsets of \{onset, rime, tone\} exchanged between "
                 r"the two positions. Each is an involution; reading an output in the other order maps \var{1} to \var{6}, "
                 r"\var{2} to \var{3} and \var{4} to \var{5}, so \var{5} and \var{6} add no new unordered pair and are not "
                 r"generated as \task{T1} cells. Examples \var{1}--\var{5} are attested folk forms that the engine reproduces "
                 r"exactly; \var{6} has none.}")
    lines.append(r"\label{tab:variants}")
    lines.append(r"\end{table}")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=ROOT / "paper" / "tables")
    args = ap.parse_args(argv)
    args.out.mkdir(parents=True, exist_ok=True)
    now = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%MZ")
    written = {}
    (args.out / "rules_components.tex").write_text(components_table(now), encoding="utf-8")
    (args.out / "rules_onsets.tex").write_text(onsets_table(now), encoding="utf-8")
    (args.out / "rules_spelling.tex").write_text(spelling_table(now), encoding="utf-8")
    (args.out / "rules_variants.tex").write_text(variants_table(now), encoding="utf-8")
    pairs = placement_pairs()
    if len(pairs) != EXPECTED_PLACEMENT_PAIRS:
        raise SystemExit(f"expected {EXPECTED_PLACEMENT_PAIRS} placement pairs, found {len(pairs)}")
    (args.out / "rules_placement.tex").write_text(placement_table(now, pairs), encoding="utf-8")
    written = {"tables": sorted(p.name for p in args.out.glob("rules_*.tex")), "n_placement_pairs": len(pairs),
               "n_onsets": len(CANONICAL_ONSETS), "n_nuclei": len(NUCLEI), "n_codas": len(CODAS)}
    print(json.dumps(written, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
