#!/usr/bin/env python
"""Appendix A: the exact prompts, rendered by the evaluation harness itself.

    python paper/gen_prompt_appendix.py --out paper/tables/prompt_examples.tex

For one example item per task (T1 meo cai / V1; T2 its noi lai form; T3 a spelling twin),
`noilai.eval.prompts.render` produces the Vietnamese p0 template with three demonstrations
(shots=3, explained instructions, raw input format, NFC arm), exactly as a model receives
it. The text is escaped for LaTeX and set in a quote environment; a JSON sidecar records
the prompt hashes so that the appendix can be tied to the run manifests. The example items
are built here and are not benchmark items (they carry no canary).

[NATIVE-CHECK] Every Vietnamese string comes from prompts/noilai.yaml and awaits native
validation there; this script only typesets it.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from noilai.eval import prompts as P  # noqa: E402
from noilai.gen import variants as V  # noqa: E402
from noilai.gen.generate import syl_dict  # noqa: E402
from noilai.vi.syllable import spell, try_parse  # noqa: E402

_ESC = {"\\": r"\textbackslash{}", "{": r"\{", "}": r"\}", "$": r"\$", "&": r"\&", "#": r"\#", "%": r"\%",
        "_": r"\_", "^": r"\textasciicircum{}", "~": r"\textasciitilde{}", "<": r"\textless{}",
        ">": r"\textgreater{}", '"': r"\textquotedbl{}"}


def tex_escape(s: str) -> str:
    return "".join(_ESC.get(ch, ch) for ch in s)


def to_quote(text: str) -> str:
    """Paragraphs separated by blank lines; line breaks inside a paragraph kept with \\\\."""
    paras = [p for p in text.split("\n\n")]
    out = []
    for p in paras:
        lines = [tex_escape(ln) for ln in p.split("\n") if ln.strip() != ""]
        if not lines:
            continue
        out.append(" \\\\\n".join(lines))
    return "\n\n".join(out)


def example_items() -> list[tuple[str, dict]]:
    a, b = (try_parse(s).syllable for s in ("mèo", "cái"))
    x, y = V.apply("V1", a, b)
    t1 = {"item_id": "example-T1", "task": "T1", "variant": "V1", "input": f"{spell(a)} {spell(b)}",
          "input_syllables": [syl_dict(a), syl_dict(b)], "gold": [f"{spell(x)} {spell(y)}"]}
    t2 = {"item_id": "example-T2", "task": "T2", "variant": "V1", "input": f"{spell(x)} {spell(y)}",
          "input_syllables": [syl_dict(x), syl_dict(y)],
          "gold": [{"variant": "V1", "reversed": False, "output": t1["input"]}]}
    # a spelling twin: c for k before e (the engine's own misspelling construction is in the generator;
    # here the twin is written out because the example is fixed)
    t3 = {"item_id": "example-T3", "task": "T3", "variant": "V1", "input": t1["input"], "candidate": "mài céo",
          "correct_output": t1["gold"][0], "gold": "no", "twin_type": "spelling"}
    return [("T1", t1), ("T2", t2), ("T3", t3)]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=ROOT / "paper" / "tables" / "prompt_examples.tex")
    ap.add_argument("--paraphrase", default="p0")
    ap.add_argument("--shots", type=int, default=3)
    args = ap.parse_args(argv)
    now = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%MZ")
    hashes = P.prompt_file_hashes()
    lines = [f"% GENERATED by paper/gen_prompt_appendix.py on {now} from prompts/noilai.yaml + prompts/demos.yaml; do not edit.",
             "% prompt file sha256: " + ", ".join(f"{Path(k).name}={v[:12]}" for k, v in hashes.items())]
    side = {"generated": now, "prompt_file_sha256": hashes, "paraphrase": args.paraphrase, "shots": args.shots, "examples": []}
    titles = {"T1": "Transformation (\\task{T1}), variant \\var{1}, paraphrase p0, three demonstrations",
              "T2": "Decoding (\\task{T2}), paraphrase p0, three demonstrations (the variant is withheld)",
              "T3": "Validity (\\task{T3}), variant \\var{1}, paraphrase p0, a spelling twin as candidate"}
    for task, item in example_items():
        msgs = P.render(item, paraphrase=args.paraphrase, shots=args.shots, arm="nfc")
        content = msgs[-1]["content"]
        pid = P.prompt_id(args.paraphrase, args.shots)
        h = P.prompt_hash(msgs)
        side["examples"].append({"task": task, "item": item, "prompt_id": pid, "prompt_hash": h, "content": content})
        lines.append(rf"\paragraph{{{titles[task]}.}} Prompt id \texttt{{{tex_escape(pid)}}}, sha256 \texttt{{{h[:12]}}}.")
        lines.append(r"\begin{quote}\small")
        lines.append(to_quote(content))
        lines.append(r"\end{quote}")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    args.out.with_suffix(".json").write_text(json.dumps(side, ensure_ascii=False, indent=1), encoding="utf-8")
    print(json.dumps({"out": str(args.out), "examples": [(e["task"], e["prompt_hash"][:12]) for e in side["examples"]]}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
